export const listaLogradouro = [
  { id: 8, descricao: "AVENIDA" },
  { id: 81, descricao: "RUA" },
  { id: 100, descricao: "TRAVESSA" },
  { id: 101, descricao: "VIA" },
  { id: 645, descricao: "ACAMPAMENTO" },
  { id: 1, descricao: "ACESSO" },
  { id: 2, descricao: "ADRO" },
  { id: 501, descricao: "AEROPORTO" },
  { id: 4, descricao: "ALAMEDA" },
  { id: 5, descricao: "ALTO" },
  { id: 472, descricao: "AREA" },
  { id: 465, descricao: "ARTERIA" },
  { id: 7, descricao: "ATALHO" },
  { id: 15, descricao: "BAIXA" },
  { id: 470, descricao: "BALAO" },
  { id: 9, descricao: "BALNEARIO" },
  { id: 11, descricao: "BECO" },
  { id: 10, descricao: "BELVEDERE" },
  { id: 12, descricao: "BLOCO" },
  { id: 13, descricao: "BOSQUE" },
  { id: 14, descricao: "BOULEVARD" },
  { id: 496, descricao: "BURACO" },
  { id: 16, descricao: "CAIS" },
  { id: 571, descricao: "CALCADA" },
  { id: 17, descricao: "CAMINHO" },
  { id: 23, descricao: "CAMPO" },
  { id: 495, descricao: "CANAL" },
  { id: 481, descricao: "CHACARA" },
  { id: 19, descricao: "CHAPADAO" },
  { id: 479, descricao: "CIRCULAR" },
  { id: 21, descricao: "COLONIA" },
  { id: 503, descricao: "COMPLEXO VIARIO" },
  { id: 485, descricao: "CONDOMINIO" },
  { id: 20, descricao: "CONJUNTO" },
  { id: 22, descricao: "CORREDOR" },
  { id: 24, descricao: "CORREGO" },
  { id: 478, descricao: "DESCIDA" },
  { id: 27, descricao: "DESVIO" },
  { id: 28, descricao: "DISTRITO" },
  { id: 468, descricao: "ELEVADA" },
  { id: 573, descricao: "ENTRADA PARTICULAR" },
  { id: 30, descricao: "ESCADA" },
  { id: 474, descricao: "ESPLANADA" },
  { id: 32, descricao: "ESTACAO" },
  { id: 564, descricao: "ESTACIONAMENTO" },
  { id: 33, descricao: "ESTADIO" },
  { id: 498, descricao: "ESTANCIA" },
  { id: 31, descricao: "ESTRADA" },
  { id: 36, descricao: "FAVELA" },
  { id: 37, descricao: "FAZENDA" },
  { id: 40, descricao: "FEIRA" },
  { id: 38, descricao: "FERROVIA" },
  { id: 39, descricao: "FONTE" },
  { id: 43, descricao: "FORTE" },
  { id: 45, descricao: "GALERIA" },
  { id: 46, descricao: "GRANJA" },
  { id: 486, descricao: "HABITACIONAL" },
  { id: 50, descricao: "ILHA" },
  { id: 52, descricao: "JARDIM" },
  { id: 473, descricao: "JARDINETE" },
  { id: 53, descricao: "LADEIRA" },
  { id: 499, descricao: "LAGO" },
  { id: 55, descricao: "LAGOA" },
  { id: 54, descricao: "LARGO" },
  { id: 56, descricao: "LOTEAMENTO" },
  { id: 477, descricao: "MARINA" },
  { id: 497, descricao: "MODULO" },
  { id: 60, descricao: "MONTE" },
  { id: 59, descricao: "MORRO" },
  { id: 500, descricao: "NUCLEO" },
  { id: 67, descricao: "PARADA" },
  { id: 471, descricao: "PARADOURO" },
  { id: 62, descricao: "PARALELA" },
  { id: 72, descricao: "PARQUE" },
  { id: 74, descricao: "PASSAGEM" },
  { id: 502, descricao: "PASSAGEM SUBTERRANEA" },
  { id: 73, descricao: "PASSARELA" },
  { id: 63, descricao: "PASSEIO" },
  { id: 64, descricao: "PATIO" },
  { id: 483, descricao: "PONTA" },
  { id: 76, descricao: "PONTE" },
  { id: 469, descricao: "PORTO" },
  { id: 65, descricao: "PRACA" },
  { id: 504, descricao: "PRACA DE ESPORTES" },
  { id: 70, descricao: "PRAIA" },
  { id: 71, descricao: "PROLONGAMENTO" },
  { id: 77, descricao: "QUADRA" },
  { id: 79, descricao: "QUINTA" },
  { id: 475, descricao: "QUINTAS" },
  { id: 82, descricao: "RAMAL" },
  { id: 482, descricao: "RAMPA" },
  { id: 87, descricao: "RECANTO" },
  { id: 487, descricao: "RESIDENCIAL" },
  { id: 89, descricao: "RETA" },
  { id: 88, descricao: "RETIRO" },
  { id: 91, descricao: "RETORNO" },
  { id: 569, descricao: "RODO ANEL" },
  { id: 90, descricao: "RODOVIA" },
  { id: 506, descricao: "ROTATORIA" },
  { id: 476, descricao: "ROTULA" },
  { id: 566, descricao: "RUA DE PEDESTRE" },
  { id: 94, descricao: "SERVIDAO" },
  { id: 95, descricao: "SETOR" },
  { id: 92, descricao: "SITIO" },
  { id: 96, descricao: "SUBIDA" },
  { id: 98, descricao: "TERMINAL" },
  { id: 570, descricao: "TRAVESSA PARTICULAR" },
  { id: 452, descricao: "TRECHO" },
  { id: 99, descricao: "TREVO" },
  { id: 97, descricao: "TRINCHEIRA" },
  { id: 567, descricao: "TUNEL" },
  { id: 480, descricao: "UNIDADE" },
  { id: 565, descricao: "VALA" },
  { id: 106, descricao: "VALE" },
  { id: 568, descricao: "VARIANTE" },
  { id: 453, descricao: "VEREDA" },
  { id: 572, descricao: "VIA DE ACESSO" },
  { id: 484, descricao: "VIA DE PEDESTRE" },
  { id: 505, descricao: "VIA ELEVADA" },
  { id: 646, descricao: "VIA EXPRESSA" },
  { id: 103, descricao: "VIADUTO" },
  { id: 105, descricao: "VIELA" },
  { id: 104, descricao: "VILA" },
  { id: 108, descricao: "ZIGUE-ZAGUE" },
  { id: 552, descricao: "1ª RUA" },
  { id: 507, descricao: "1ª TRAVESSA" },
  { id: 561, descricao: "10ª RUA" },
  { id: 562, descricao: "11ª RUA" },
];
